name: ğŸš€ DÃ©ploiement Git AutomatisÃ©

on:
  push:
    branches:
      - main
      - back
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ§¾ RÃ©cupÃ©ration du code
      uses: actions/checkout@v3

    - name: âš™ï¸ Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: ğŸ“¦ Installation des dÃ©pendances (si besoin)
      run: |
        pip install -r requirements.txt || echo "Pas de dÃ©pendances"

    - name: ğŸš€ Lancer le script de dÃ©ploiement
      run: |
        python depot.py
